version: '3'

services:

  # redis
  redis:
    image: redis:latest
    container_name: feng-redis
    restart: always
    ports:
      - "6479:6379"
    volumes:
      - "./redis/6379/data:/data"

  mongo:
    image: mongo:4.0.23
    container_name: feng-mongo
    restart: always
    volumes:
      - "./mongo/data:/data/db"
    ports:
      - "27117:27017"

  feng:
    build: .
    container_name: feng
    restart: always
    ports:
      - "12445:12345" # ops swagger走12445端口
      - "10100:10100" # ops 调用接口走 10100 nginx端口
    volumes:
      - ".:/feng-admin"
    command: ["sh","/feng-admin/start.sh"]
    tty: true
